# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2024.04.23
_src_path: gh:scientific-python/cookie
backend: hatch
email: nstarman@users.noreply.github.com
full_name: GalacticDynamics Maintainers
license: MIT
org: GalacticDynamics
project_name: optional_dependencies
project_short_description: Construct Checks for Optional Dependencies
url: https://github.com/GalacticDynamics/optional_dependencies
vcs: true
